# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/tmp/pins.xdc

# Block Designs: bd/zynq_ps_bd/zynq_ps_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_ps_bd || ORIG_REF_NAME==zynq_ps_bd} -quiet] -quiet

# IP: bd/zynq_ps_bd/ip/zynq_ps_bd_processing_system7_0_0/zynq_ps_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq_ps_bd_processing_system7_0_0 || ORIG_REF_NAME==zynq_ps_bd_processing_system7_0_0} -quiet] -quiet

# XDC: e:/vivadoprojects/ibex_soc/ibex_soc.gen/sources_1/bd/zynq_ps_bd/zynq_ps_bd_ooc.xdc
