# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/vivadoprojects/ibex_soc/ibex_soc.runs/synth_1/ibex_soc_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z015clg485-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/vivadoprojects/ibex_soc/ibex_soc.cache/wt [current_project]
set_property parent.project_path E:/vivadoprojects/ibex_soc/ibex_soc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/vivadoprojects/ibex_soc/ibex_soc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_assert_dummy_macros.svh
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_assert_sec_cm.svh
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/dv/sv/dv_utils/dv_fcov_macros.svh
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_util_memload.svh
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_util_get_scramble_params.svh
}
set_property file_type "Verilog Header" [get_files E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_assert_dummy_macros.svh]
set_property file_type "Verilog Header" [get_files E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_assert_sec_cm.svh]
set_property file_type "Verilog Header" [get_files E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/dv/sv/dv_utils/dv_fcov_macros.svh]
set_property file_type "Verilog Header" [get_files E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_util_memload.svh]
set_property file_type "Verilog Header" [get_files E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_util_get_scramble_params.svh]
read_verilog -library xil_defaultlib -sv {
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/tmp/bram_mem.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_pkg.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_alu.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_assert.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_flop_macros.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_branch_predict.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_compressed_decoder.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_controller.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_core.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_counter.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_cs_registers.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_csr.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_decoder.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_dummy_instr.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_ex_block.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_fetch_fifo.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_icache.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_id_stage.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_if_stage.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_load_store_unit.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_pkg.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_util_pkg.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_lockstep.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_multdiv_fast.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_multdiv_slow.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_pmp.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_prefetch_buffer.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_register_file_ff.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_register_file_fpga.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_register_file_latch.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_ram_1p_pkg.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_top.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/rtl/ibex_wb_stage.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_mubi_pkg.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_buf.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_cipher_pkg.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_clock_gating.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_clock_mux2.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_count_pkg.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_count.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_flop.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_lfsr.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_prince.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim_generic/rtl/prim_ram_1p.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_ram_1p_adv.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_ram_1p_scr.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_22_16_dec.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_22_16_enc.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_28_22_dec.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_28_22_enc.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_39_32_dec.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_39_32_enc.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_hamming_22_16_dec.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_hamming_22_16_enc.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_hamming_39_32_dec.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_inv_hamming_39_32_enc.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_subst_perm.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/rtl/simple_gpio.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/rtl/soc_bus.sv
  E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/imports/tmp/ibex_soc_top.sv
}
read_verilog -library xil_defaultlib e:/vivadoprojects/ibex_soc/ibex_soc.gen/sources_1/bd/zynq_ps_bd/hdl/zynq_ps_bd_wrapper.v
add_files E:/vivadoprojects/ibex_soc/ibex_soc.srcs/sources_1/bd/zynq_ps_bd/zynq_ps_bd.bd
set_property used_in_implementation false [get_files -all e:/vivadoprojects/ibex_soc/ibex_soc.gen/sources_1/bd/zynq_ps_bd/ip/zynq_ps_bd_processing_system7_0_0/zynq_ps_bd_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/vivadoprojects/ibex_soc/ibex_soc.gen/sources_1/bd/zynq_ps_bd/zynq_ps_bd_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/vivadoprojects/ibex_soc/ibex_soc.srcs/constrs_1/imports/tmp/pins.xdc
set_property used_in_implementation false [get_files E:/vivadoprojects/ibex_soc/ibex_soc.srcs/constrs_1/imports/tmp/pins.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental E:/vivadoprojects/ibex_soc/ibex_soc.srcs/utils_1/imports/synth_1/ibex_soc_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top ibex_soc_top -part xc7z015clg485-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ibex_soc_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file ibex_soc_top_utilization_synth.rpt -pb ibex_soc_top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
